Repository brazil-data-cube/cube-builder-aws, pull requests merged in 2021-01, with the labels that each got.

#89 update cog generate and fix pos_blend
  cube-builder-aws/cube_builder_aws/maestro.py
  cube-builder-aws/cube_builder_aws/utils/builder.py
  cube-builder-aws/cube_builder_aws/utils/constants.py
  cube-builder-aws/requirements.txt
  cube-builder-aws/serverless.yml
Labels: bug, enhancement

#100 update structure - close #91
  .gitignore
  cube-builder-aws/app.py
  cube-builder-aws/cube_builder_aws/__init__.py
  cube-builder-aws/cube_builder_aws/config.py
  cube-builder-aws/cube_builder_aws/constants.py
  cube-builder-aws/cube_builder_aws/controller.py
  cube-builder-aws/cube_builder_aws/forms.py
  cube-builder-aws/cube_builder_aws/maestro.py
  cube-builder-aws/cube_builder_aws/services.py
  cube-builder-aws/cube_builder_aws/utils/__init__.py
  cube-builder-aws/cube_builder_aws/utils/processing.py
  cube-builder-aws/cube_builder_aws/views.py
  cube-builder-aws/requirements.txt
Labels: enhancement

#102 close #82 - compute checksum of bucket objects
  cube-builder-aws/cube_builder_aws/services.py
  cube-builder-aws/cube_builder_aws/utils/processing.py
Labels: enhancement

#103 Upgrade bdc-catalog to 0.8.0
  cube-builder-aws/requirements.txt
Labels: enhancement

#105 update endpoint responsible for managing cube metadata
  cube-builder-aws/cube_builder_aws/constants.py
  cube-builder-aws/cube_builder_aws/controller.py
  cube-builder-aws/cube_builder_aws/utils/processing.py
  cube-builder-aws/cube_builder_aws/validators.py
  cube-builder-aws/cube_builder_aws/views.py
Labels: enhancement

#108 Adapt the timeline creation
  cube-builder-aws/cube_builder_aws/controller.py
  cube-builder-aws/cube_builder_aws/maestro.py
  cube-builder-aws/cube_builder_aws/utils/timeline.py
Labels: enhancement

#110 close #109 - fix wrong cloud cover
  cube-builder-aws/cube_builder_aws/utils/processing.py
Labels: bug

#112 format endpoints and remove cerberus
  cube-builder-aws/cube_builder_aws/controller.py
  cube-builder-aws/cube_builder_aws/forms.py
  cube-builder-aws/cube_builder_aws/validators.py
  cube-builder-aws/cube_builder_aws/views.py
  cube-builder-aws/requirements.txt
Labels: bug

#114 add shape params if not is BDC grid - close #95
  cube-builder-aws/cube_builder_aws/controller.py
  cube-builder-aws/cube_builder_aws/maestro.py
  cube-builder-aws/cube_builder_aws/views.py
Labels: enhancement

#113 Add support of custom cloud mask values -sen2cor and fmask
  cube-builder-aws/cube_builder_aws/maestro.py
  cube-builder-aws/cube_builder_aws/utils/processing.py
Labels: enhancement

#115 Add support to use secondary stac catalog to search for collection
  cube-builder-aws/cube_builder_aws/maestro.py
  cube-builder-aws/cube_builder_aws/services.py
Labels: enhancement
